
# Site settings
title: GAIA laboratory
subtitle:
baseurl: #gaia
url: # https://baobablab.github.io/

# Contacts
email: edouard.duchesnay@cea.fr
author:
street_address:
city:
state: 
zip_code:
country: France
phone:

# Expiration in days
expiration_opportunities: 200
expiration_news: 300

# Social settings
#500px_url: http://www.neurospin-wiki.org/pmwiki/Main/DirectionsToNeurospin
#facebook_url: https://www.facebook.com/pages/NeuroSpin/171075046414933
#github_url: https://github.com/neurospin
#twitter_url: https://twitter.com/neurospin_91
#youtube_url: https://www.youtube.com/CEASaclay
map_url: https://www.google.fr/maps/@48.720535,2.1467526,16z?hl=en

# Sass building
sass:
    sass_dir: _sass
    
# Build settings
markdown: kramdown

# Collections
collections_dir: _collections
collections:

  opportunities:
    output    : true
    permalink : /:collection/:path

  collaborators:
    output    : true
    permalink : /colleborators/:title/index.html

  people:
    output    : true
    permalink : /people/:title/index.html

  news:
    output    : true
    permalink : /news/:title/index.html

  biblio:
    output    : true
    permalink : /biblio/:title/index.html

  research:
    output    : true
    permalink : /research/:title/index.html

  labs:
    output    : true
    permalink : /labs/:title/index.html

